### ISSUE TITLE
https failed

### ISSUE THREAD

**Issue by chengdi1988** [thingsboard/python_tb_rest_client#10]
os: win10
server: CE 3.2.0
client: `pip install tb_rest_client32`

problem: 
```python
from tb_rest_client32.rest_client_ce import *
from tb_rest_client32.rest import ApiException
base_url = "https://test2.bj-jiashi.com:10005"
rest_client = RestClientCE(base_url=base_url)
rest_client.configuration.verify_ssl=r'config\rootCA.pem'
rest_client.login(username="tenant@thingsboard.org", password="xxx") # works

# Creating an Asset
asset = Asset(name="Building 1", type="building")
asset = rest_client.save_asset(asset) # raise error
```
error:
```
2021-03-07 11:17:24,254 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /api/asset
2021-03-07 11:17:24,303 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /api/asset
2021-03-07 11:17:24,354 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))': /api/asset
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "C:\ProgramData\Miniconda3\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\ProgramData\Miniconda3\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\ProgramData\Miniconda3\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connection.py", line 360, in connect
    ssl_context=context,
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\rest_client_base.py", line 118, in save_asset
    return self.asset_controller.save_asset_using_post(asset, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\api\api_ce\asset_controller_api.py", line 1371, in save_asset_using_post
    (data) = self.save_asset_using_post_with_http_info(asset, **kwargs)  # noqa: E501
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\api\api_ce\asset_controller_api.py", line 1443, in save_asset_using_post_with_http_info     
    collection_formats=collection_formats)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\api_client.py", line 423, in call_api
    _preload_content, _request_timeout)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\api_client.py", line 198, in __call_api
    _request_timeout=_request_timeout)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\api_client.py", line 466, in request
    body=body)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\rest.py", line 278, in POST
    body=body)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tb_rest_client32\rest.py", line 170, in request
    headers=headers)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test2.bj-jiashi.com', port=10005): Max retries exceeded with url: /api/asset (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

discuss:
requests works for some cases
```python
# works if ignore https
requests.get(base_url,verify=False)
# works if using rootCA.pem generated by mkcert
requests.get(base_url,verify=r'config\rootCA.pem')
# work if using chrome exported cert in base64 format
requests.get(base_url,verify=r'config\base64_x509_rootCA.cer')
# fail if using chrome exported cert in der format
requests.get(base_url,verify=r'config\der_x509_rootCA.cer')
```

**Comment by samson0v** [comment]
Hi @chengdi1988, it seems that your certificate is not valid, please make sure that you correctly generate it.
