### ISSUE TITLE
get_timeseries_keys() - 'str' object has no attribute 'entity_type'

### ISSUE THREAD

**Issue by voxic** [thingsboard/python_tb_rest_client#4]
Hi I'm trying to fetch get_temeseries_keys but get an AttributeError in the call chain.

**My calling code:**
```
        rest_client.login(username=username, password=password)

        device = rest_client.get_tenant_device("Thermometer 1")
        print(device)
        rest_client.get_timeseries_keys(device.id.id)
```
**Output:**
```
{'additional_info': None,
 'created_time': 1596020419660,
 'customer_id': {'entity_type': 'CUSTOMER',
                 'id': '13814000-1dd2-11b2-8080-808080808080'},
 'id': {'entity_type': 'DEVICE', 'id': 'b12f98c0-d18a-11ea-a2d4-05d67df22d46'},
 'label': None,
 'name': 'Thermometer 1',
 'owner_id': None,
 'tenant_id': {'entity_type': 'TENANT',
               'id': '1a3b3000-d18a-11ea-a2d4-05d67df22d46'},
 'type': 'thermometer'}
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    rest_client.get_timeseries_keys(device.id.id)
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/rest_client_base.py", line 622, in get_timeseries_keys
    return self.telemetry_controller.get_timeseries_keys_using_get(entity_type=entity_id.entity_type,
AttributeError: 'str' object has no attribute 'entity_type'
```

When using a device.id object instead I get another error:

**My calling code:**
```
        rest_client.login(username=username, password=password)

        device = rest_client.get_tenant_device("Thermometer 1")
        print(device)
        rest_client.get_timeseries_keys(device.id)
```

**Output:**
```
{'additional_info': None,
 'created_time': 1596020419660,
 'customer_id': {'entity_type': 'CUSTOMER',
                 'id': '13814000-1dd2-11b2-8080-808080808080'},
 'id': {'entity_type': 'DEVICE', 'id': 'b12f98c0-d18a-11ea-a2d4-05d67df22d46'},
 'label': None,
 'name': 'Thermometer 1',
 'owner_id': None,
 'tenant_id': {'entity_type': 'TENANT',
               'id': '1a3b3000-d18a-11ea-a2d4-05d67df22d46'},
 'type': 'thermometer'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/api_client.py", line 316, in __deserialize
    found_class = getattr(tb_rest_client.models.models_pe, klass)
AttributeError: module 'tb_rest_client.models.models_pe' has no attribute 'DeferredResultResponseEntity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    rest_client.get_timeseries_keys(device.id)
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/rest_client_base.py", line 622, in get_timeseries_keys
    return self.telemetry_controller.get_timeseries_keys_using_get(entity_type=entity_id.entity_type,
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/api/api_ce/telemetry_controller_api.py", line 944, in get_timeseries_keys_using_get
    (data) = self.get_timeseries_keys_using_get_with_http_info(entity_type, entity_id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/api/api_ce/telemetry_controller_api.py", line 1010, in get_timeseries_keys_using_get_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/api_client.py", line 390, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/api_client.py", line 205, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/api_client.py", line 287, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/api_client.py", line 327, in __deserialize
    if all(attr in list(found_class.attribute_map.values()) for attr in list(data.keys())):
AttributeError: 'list' object has no attribute 'keys'
```

Am I doing it wrong? Missing a lot of documentation on how to use the API.

**Comment by zbeacon** [comment]
Hi @voxic ,

It was a bug, it was solved in the release 1.1.0, please install it using following commands:
`sudo pip3 uninstall tb-rest-client -y`
and 
`sudo pip3 install tb-rest-client==1.1.0`
